#!/usr/bin/env bash
# Fix the runtime environment needed by the snapped application
#
# Copyright 2025 林博仁(Buo-ren, Lin) <buo.ren.lin@gmail.com>
# SPDX-License-Identifier: Apache-2.0

# Enable the notice window if the environment variable is set
SNAP_LAUNCHER_NOTICE_ENABLED="${SNAP_LAUNCHER_NOTICE_ENABLED:-true}"

set_opts=(
    # Terminate script execution when an unhandled error occurs
    -o errexit
    -o errtrace

    # Terminate script execution when an unset parameter variable is
    # referenced
    -o nounset
)
if ! set "${set_opts[@]}"; then
    printf \
        'Error: Unable to configure the defensive interpreter behaviors.\n' \
        1>&2
    exit 1
fi

# Only show the unofficial snap notice for new installations
installation_indicator="${SNAP_USER_DATA}/.android"
if ! test -e "${installation_indicator}"; then
    if test "${SNAP_LAUNCHER_NOTICE_ENABLED}" = "true"; then
        printf \
            '=========================\nHello!\n\nThis application is an unofficial distribution of scrcpy.\n\nTo minimize upstream annoyance, please DO NOT report snap-specific issues to the upstream scrcpy issue tracker.  Instead, report any problems to this snap'\''s issue tracker:\n\n    <https://github.com/brlin-tw/scrcpy-snap/issues>\n\nNOTE: A graphical notice is displayed with a timeout in the meantime, to skip it, set the environment variable SNAP_LAUNCHER_NOTICE_ENABLED to "false".\n=========================\n' 1>&2

        "${SNAP}/bin/unofficial-snap-notice" && ret="${?}" || ret="${?}"

        case "${ret}" in
            0)
                # User pressed ENTER, avoid showing this notice window in the future
                mkdir "${installation_indicator}"
                ;;
            1)
                # User bailed out
                exit 1
                ;;
            2)
                printf "Dialog timed out, continuing...\n"
                ;;
            *)
                # Unknown error
                printf "FATAL: Unknown unofficial-snap-notice exit status: %d\n" "${ret}" 1>&2
                exit 99
                ;;
        esac
    fi
fi

flag_otg_mode=false
flag_gamepad_mode=false
for arg in "${@:1}"; do
    case "${arg}" in
        --otg)
            flag_otg_mode=true
            ;;
        --gamepad*)
            flag_gamepad_mode=true
            ;;
        *)
            : # Do nothing
        ;;
    esac
done

marker_file="${SNAP_USER_COMMON}/.marker.skip-rawusb-interface-notice"
if ! snapctl is-connected raw-usb; then
    printf \
        '%s: Warning: The "raw-usb" snapd security confinement interface is not connected, the OTG mode will not work.\n' \
        "${0}" \
        1>&2

    if {
        ! test -e "${marker_file}" \
        && test "${SNAP_LAUNCHER_NOTICE_ENABLED}" = "true"
        } || test "${flag_otg_mode}" = "true"; then
        printf \
            '=========================\nThe following functionality requires the "raw-usb" snapd security confinement interface to be connected:\n\nOTG mode\n\nYou may do so by running the following command in a terminal:\n\n    sudo snap connect scrcpy:raw-usb\n\nNOTE: A graphical notice is displayed with a timeout in the meantime, to skip it, set the environment variable SNAP_LAUNCHER_NOTICE_ENABLED to "false".\n=========================\n' \
            1>&2

        "${SNAP}/bin/manual-interface-notice" raw-usb 'OTG mode' && ret="${?}" || ret="${?}"

        case "${ret}" in
            0)
                # User pressed ENTER, avoid showing this notice window in the future
                touch "${marker_file}"
                ;;
            1)
                # User bailed out
                exit 1
                ;;
            2)
                printf "Dialog timed out, continuing...\n"
                ;;
            *)
                # Unknown error
                printf "FATAL: Unknown sdl2-notice exit status: %d\n" "${ret}" 1>&2
                exit 99
                ;;
        esac
    fi
fi

marker_file="${SNAP_USER_COMMON}/.marker.skip-joystick-interface-notice"
if ! snapctl is-connected joystick; then
    printf \
        '%s: Warning: The "joystick" snapd security confinement interface is not connected, the Gamepad mode will not work.\n' \
        "${0}" \
        1>&2

    if {
        ! test -e "${marker_file}" \
        && test "${SNAP_LAUNCHER_NOTICE_ENABLED}" = "true"
        } || test "${flag_gamepad_mode}" = "true"; then
        printf \
            '=========================\nThe following functionality requires the "joystick" snapd security confinement interface to be connected:\n\nGamepad mode\n\nYou may do so by running the following command in a terminal:\n\n    sudo snap connect scrcpy:joystick\n\nNOTE: A graphical notice is displayed with a timeout in the meantime, to skip it, set the environment variable SNAP_LAUNCHER_NOTICE_ENABLED to "false".\n=========================\n' \
            1>&2

        "${SNAP}/bin/manual-interface-notice" joystick 'Gamepad mode' && ret="${?}" || ret="${?}"

        case "${ret}" in
            0)
                # User pressed ENTER, avoid showing this notice window in the future
                touch "${marker_file}"
                ;;
            1)
                # User bailed out
                exit 1
                ;;
            2)
                printf "Dialog timed out, continuing...\n"
                ;;
            *)
                # Unknown error
                printf "FATAL: Unknown sdl2-notice exit status: %d\n" "${ret}" 1>&2
                exit 99
                ;;
        esac
    fi
fi

if ! "${@}"; then
    printf "Warning: Application returned non-zero exit status %s.\n" "${?}" 1>&2
    exit 1
fi

if pgrep --full 'adb.*fork-server' >/dev/null; then
    if ! adb kill-server; then
        printf "Warning: Failed to stop ADB server.\n" 1>&2
        exit 1
    fi
fi
