name: scrcpy
title: scrcpy (UNOFFICIAL)
summary: Display and control your Android device
description: |
  This application mirrors Android devices (video and audio) connected
  via USB or TCP/IP and allows control using the computer's keyboard and
  mouse. It does not require root access or an app installed on the
  device.

  See https://github.com/Genymobile/scrcpy for more information.

  **Snap publisher notice**

  This is an unofficial distribution of scrcpy.  Please report any
  issues of the usage of this snap to the snap's own issue tracker:

  https://github.com/brlin-tw/scrcpy-snap/issues

  Thank you!

contact: https://github.com/brlin-tw/scrcpy-snap/issues
issues: https://github.com/brlin-tw/scrcpy-snap/issues
source-code: https://github.com/brlin-tw/scrcpy-snap
website: https://github.com/brlin-tw/scrcpy-snap

license: Apache-2.0
grade: stable
confinement: strict
compression: lzo
version: scrcpy-runtime-2404

base: core24

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  armhf:
    build-on: [armhf]
    build-for: [armhf]

plugs:
  ffmpeg-2404:
    interface: content
    target: $SNAP/ffmpeg-platform
    default-provider: ffmpeg-2404

  scrcpy-runtime-2404:
    interface: content
    target: $SNAP/scrcpy-runtime
    default-provider: scrcpy-runtime-2404

apps:
  scrcpy:
    command: bin/scrcpy-launch
    completer: usr/local/share/bash-completion/completions/scrcpy
    desktop: usr/local/share/applications/scrcpy.desktop
    environment: &scrcpy-env
      LD_LIBRARY_PATH: ${SNAP}/scrcpy-runtime/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:${SNAP}/scrcpy-runtime/usr/local/lib:${SNAP}/ffmpeg-platform/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/android:${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:${LD_LIBRARY_PATH}
      PATH: ${SNAP}/scrcpy-runtime/usr/local/bin:${PATH}
    plugs: &scrcpy-plugs
      # For running the Android Debug Bridge (adb) and
      # connecting the Android devices over USB or TCP/IP.
      # https://github.com/Genymobile/scrcpy/blob/master/doc/connection.md
      - adb-support
      - network
      - network-bind
      - raw-usb

      # For audio forwarding functionality.
      # https://github.com/Genymobile/scrcpy/blob/master/doc/audio.md
      - alsa
      - audio-playback
      - pulseaudio

      # For v4l2 emulation support.
      # https://github.com/Genymobile/scrcpy/blob/master/doc/v4l2.md
      - camera

      # For video & audio recording support.
      # https://github.com/Genymobile/scrcpy/blob/master/doc/recording.md
      - home
      - removable-media

      # For gamepad simulation support.
      # https://github.com/Genymobile/scrcpy/blob/master/doc/gamepad.md
      - joystick

      # Legacy desktop support.
      # https://github.com/canonical/snapd/blob/master/interfaces/builtin/unity7.go
      - unity7
    extensions:
      - gnome

  console:
    command: bin/scrcpy-launch
    completer: usr/local/share/bash-completion/completions/scrcpy
    desktop: usr/local/share/applications/scrcpy-console.desktop
    environment: *scrcpy-env
    plugs: *scrcpy-plugs
    extensions:
      - gnome

  adb:
    command: usr/bin/adb
    environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/android:${LD_LIBRARY_PATH}
    plugs:
      - adb-support
      - network
      - network-bind
      - raw-usb

layout:
  # WORKAROUND:
  # libproxy.so.1 (from gnome-46-2404) has a hardcoded RUNPATH of
  # /usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libproxy for loading
  # libpxbackend-1.0.so.  Map it so the dynamic linker can resolve it.
  # https://github.com/canonical/snapcraft/issues/6054
  /usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libproxy:
    symlink: $SNAP/gnome-platform/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libproxy
  # This fixes the "ERROR: Could not open icon image: /usr/local/share/icons/hicolor/256x256/apps/scrcpy.png"
  # error at runtime.
  /usr/local/share/icons:
    symlink: $SNAP/scrcpy-runtime/usr/local/share/icons
  # This allows scrcpy to locate the scrcpy-server binary.
  # "ERROR: '/usr/local/share/scrcpy/scrcpy-server' does not exist or is not a regular file"
  /usr/local/share/scrcpy:
    symlink: $SNAP/scrcpy-runtime/usr/local/share/scrcpy
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa

parts:
  scrcpy-assets:
    plugin: nil
    build-snaps:
      - scrcpy-runtime-2404
    override-build: |
      mkdir -p "${CRAFT_PART_INSTALL}/usr/local/share/applications"
      cp -a /snap/scrcpy-runtime-2404/current/usr/local/share/applications/*.desktop "${CRAFT_PART_INSTALL}/usr/local/share/applications/"

      mkdir -p "${CRAFT_PART_INSTALL}/usr/local/share/bash-completion/completions"
      cp -a /snap/scrcpy-runtime-2404/current/usr/local/share/bash-completion/completions/* "${CRAFT_PART_INSTALL}/usr/local/share/bash-completion/completions/"

  adb:
    plugin: nil
    stage-packages:
      - adb
      - android-libbase
      - android-libboringssl
      - android-libcutils
      - android-liblog
      - android-libziparchive
      - libbrotli1
      - libcap2
      - liblz4-1
      - libprotobuf32t64
      - libudev1
      - libusb-1.0-0
      - libzstd1
    stage:
      - -usr/lib/x86_64-linux-gnu/libpsx.so*

  # Launcher programs to fix problems at runtime
  launchers:
    source: snap/local/launchers
    plugin: dump
    organize:
      '*': bin/
    stage:
      - -bin/README.*
      - -bin/sdl2-notices

  launchers-notice:
    source: snap/local/launchers/sdl2-notices
    plugin: nil
    override-build: |
      craftctl default
      mkdir -p "${SNAPCRAFT_PART_INSTALL}/bin"

      for notice in \
        unofficial-snap-notice \
        manual-interface-notice; do
        # NOTE: The lack of quotes around the `pkg-config` command substitution is intentional.
        gcc \
          -o "${SNAPCRAFT_PART_INSTALL}/bin/${notice}" \
          "${CRAFT_PROJECT_DIR}/snap/local/launchers/sdl2-notices/${notice}.c" \
          $(pkg-config --cflags --libs sdl2 SDL2_ttf)
      done
    build-packages:
      - libsdl2-dev
      - libsdl2-ttf-dev
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-ttf-2.0-0
    stage:
      # WORKAROUND: Avoid the "Parts 'scrcpy' and 'launchers-notice' list the following files, but with different contents or permissions" error on armhf
      # On that architecture the libasound library is diverted to liboss4-salsa hence the contents of the file is different.
      - -usr/lib/*/libasound.so.2*

      - -usr/lib/*/libharfbuzz.so*
      - -usr/lib/*/libicui18n.so*
      - -usr/lib/*/libicuio.so*
      - -usr/lib/*/libicutest.so*
      - -usr/lib/*/libicutu.so*
      - -usr/lib/*/libpulse-simple.so*

      # Provided by the mesa-2404 content snap
      - -usr/lib/*/libdrm_amdgpu.so*
      - -usr/lib/*/libdrm_intel.so*
      - -usr/lib/*/libgallium-*.so*

  gpu-2404:
    after:
      - scrcpy-assets
      - launchers-notice
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
      # Workaround for https://bugs.launchpad.net/snapd/+bug/2055273
      mkdir -p "${CRAFT_PRIME}/gpu-2404"
    prime:
      - bin/gpu-2404-wrapper

  lp-bug-2016358-workaround:
    plugin: nil
    override-prime: |
      set -eu
      craftctl default
      mkdir -p "${CRAFT_PRIME}/"{ffmpeg-platform,gpu-2404,data-dir/{icons,sounds,themes},scrcpy-runtime}

lint:
  ignore:
    - library:
        # Required by the SDL2 library to prevent the "ERROR: Could not create renderer: Couldn't find matching render driver" error
        - usr/lib/*/libGLX_mesa.so*
        - usr/lib/*/libxcb-glx.so*

        # Workaround for the "Parts 'scrcpy' and 'launchers-notice' list the following files, but with different contents or permissions" error on armhf
        - usr/lib/*/libasound.so.2*

        # Required for core functionality at least on amd64 architecture
        # If not staged, the application will fail to start with the following error:
        # "ERROR: Could not create renderer: Couldn't find matching render driver"
        - usr/lib/*/libXxf86vm.so*
